[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
app_client = { path = "../app_client" }
rpc = { path = "../rpc" }
anyhow = "1.0"
tokio = { version = "1", features = ["time"] }
